apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
spec:
  type: {{ $.Values.service.type }}
  ports:
  - port: {{ $.Values.service.http.port }}
    targetPort: {{ $.Values.service.http.targetPort }}
    name: {{ $.Values.service.http.name }}
  selector:
    app: {{ .Chart.Name }}